[package]
name = "raddy-abi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ulid.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
